language: python
python:
  - "3.4"
sudo: required
services:
  - docker
before_install:
  - pip3 install codeclimate-test-reporter
script:
  - invoke unit-test
  - invoke test-install
  - invoke lint-module
  - invoke lint-tests
  - invoke build-docs
after_success:
  - codeclimate-test-reporter
