language: python
python:
  - "3.4"
sudo: required
services:
  - docker
before_install:
  - pip3 install codeclimate-test-reporter
script:
  - invoke unit-test
  - invoke test-install
  - invoke lint-module
  - invoke lint-tests
  - invoke build-docs
after_success:
  - codeclimate-test-reporter
deploy:
  provider: pypi
  user: vimist
  password:
    secure: >
      kjxvhBJNfvcrUZZPVBKdRMvswq7BXLAQMHDfQ/00BAENutq4MyMON9cYU23PumJq+0w5bafuz
      BBWch8Vn11ZLFMmbhYUBWrLtdz4zmkj0bqOqlf0eE/k7lpWzKcbSNgNM/0IGyb8G4x2yf5Io3
      BVDwZgcfDtEdL1P9z+IIIlaoxpOznSHnojlWO3+yuB5TKRE18gOS8ZnRvQGQNmxhf5wOntIgS
      6+ivHoS8ufB+iB+cZ5CQbmkvdAarNqZxwIacz1PilJ8SxnN9yVCbPCdE/e1TywJkc6BCHqrTR
      UiFaNvIGKsCYgqkC2qk0IFV2JYLmEB2nx3i8OA4kc+2xtXbewUfzCY1kgaIo/BvHcaYrVfSgd
      z04LHHtfoDwEwTZrdBwUevG4Y8hrW708BLEVIeS0600sMJj9wpEivn4JRiZmjjkFbORDPe6Kh
      bgY5f/vslPdJdqYA8fsU022f8hUCv7ZaOiuZKNa3D1K2pp92AroumEs6gtksO+Ht5yab1DwFv
      EZN2N+/MLTI3teirk3ShNTHWwKLI4h9ABkwTEVp/Xpf7GihhV5aYUADXSOaFS2P37bRGe1LMm
      +W0GfYBb9uYAXZ7UuknNrRVdDrIvJgyPcdW1XcYtbaxK6z2KHKSZmmexB2CY1bSjtX5C0BPjH
      Rvj8OUOqRusGLZw1QPdkYxrEcI=
  on:
    tags: true
